# Generated by Django 4.1.5 on 2023-01-17 20:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoapClaim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emailAddress', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('decription', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to=api.models.img_path)),
                ('address', models.FileField(blank=True, null=True, upload_to=api.models.address_path)),
                ('howMany', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
