# Generated by Django 4.1.5 on 2023-01-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_poapclaim_directpoapclaim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directpoapclaim',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='directpoapclaim',
            old_name='emailAddress',
            new_name='email',
        ),
    ]
