# Generated by Django 4.1.5 on 2023-01-19 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_decription_directpoapclaim_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpoapclaim',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directpoapclaim',
            name='imgIpfs',
            field=models.CharField(default='', max_length=500),
        ),
    ]
