# Generated by Django 4.1.5 on 2023-01-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_directpoapclaim_created_directpoapclaim_imgipfs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directpoapclaim',
            old_name='imgIpfs',
            new_name='imgCid',
        ),
    ]
