# Generated by Django 4.1.5 on 2023-01-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_imgipfs_directpoapclaim_imgcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpoapclaim',
            name='idPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directpoapclaim',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
