# Generated by Django 4.1.5 on 2023-01-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_directpoapclaim_idpaid_directpoapclaim_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directpoapclaim',
            old_name='idPaid',
            new_name='isPaid',
        ),
    ]
