# Generated by Django 4.1.5 on 2023-01-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_directpoapclaim_whopaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpoapclaim',
            name='whoPaid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
