# Generated by Django 4.1.5 on 2023-01-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_directpoapclaim_whopaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpoapclaim',
            name='txHash',
            field=models.CharField(default='', max_length=200),
        ),
    ]
