# Generated by Django 4.1.5 on 2023-01-22 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_directpoapclaim_txhash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directpoapclaim',
            old_name='txHash',
            new_name='paidTxHash',
        ),
        migrations.AddField(
            model_name='directpoapclaim',
            name='metaCid',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='directpoapclaim',
            name='uriTxHash',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='DirectPoapReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('txHash', models.CharField(default='', max_length=200)),
                ('blockNumber', models.CharField(default='', max_length=200)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.directpoapclaim')),
            ],
        ),
    ]
