# Generated by Django 4.1.5 on 2023-01-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_txhash_directpoapclaim_paidtxhash_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectPoapClaim',
            new_name='PoapClaim',
        ),
        migrations.RenameModel(
            old_name='DirectPoapReceipt',
            new_name='PoapReceipt',
        ),
    ]
