# Generated by Django 4.1.5 on 2023-01-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_directpoapclaim_poapclaim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poapclaim',
            name='secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
